class UserNotFoundError(Exception):
    pass


class UserExistsError(Exception):
    pass


class AuthError(Exception):
    pass
